name: CI Pipeline

on:
  push:
    branches:
      - RS-1
  pull_request:
    branches:
      - RS-1

jobs:
  test_and_build_client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated from v2 to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Ensure it's the latest version
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd client && npm install

    - name: Run client tests
      run: cd client && npm run test
      env:
        CI: true
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

    - name: Build client
      run: cd client && npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
